version: '3'
services:
  mpt_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
      - mpt_app_venv:/app/.venv
    command: poetry run uvicorn mpt_app.main:app --host 0.0.0.0 --reload
  mpt_ui:
    build: 
      context: ./mpt_ui
      dockerfile: ../Dockerfile.ui
    ports:
      - "3000:3000"
    volumes:
      - ./mpt_ui:/app
      - mpt_ui_node_modules:/app/node_modules
    depends_on:
      - mpt_app
    command: yarn dev
  
  db:
    image: mysql:8.0
    container_name: db
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'mpt'
      TZ: 'Asia/Tokyo'
    volumes:
      - mpt-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mpt-data:  
  mpt_ui_node_modules:
  mpt_app_venv: