"""change name to unit

Revision ID: 3ab576ee89a4
Revises: 3d37a7bfde69
Create Date: 2023-07-21 13:28:44.371872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ab576ee89a4'
down_revision = '3d37a7bfde69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector

    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if not 'units' in tables:
        op.create_table('units',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('school_year', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
        op.create_index(op.f('ix_units_school_year'), 'units', ['school_year'], unique=False)
        op.create_index(op.f('ix_units_title'), 'units', ['title'], unique=True)
        op.drop_index('ix_chapters_id', table_name='chapters')
        op.drop_index('ix_chapters_school_year', table_name='chapters')
        op.drop_index('ix_chapters_title', table_name='chapters')
    op.drop_constraint('problems_ibfk_1', 'problems', type_='foreignkey')
    op.drop_table('chapters')
    op.add_column('problems', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problems', 'units', ['unit_id'], ['id'])
    op.drop_column('problems', 'chapter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('chapter_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.create_foreign_key('problems_ibfk_1', 'problems', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('problems', 'unit_id')
    op.create_table('chapters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('school_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chapters_title', 'chapters', ['title'], unique=False)
    op.create_index('ix_chapters_school_year', 'chapters', ['school_year'], unique=False)
    op.create_index('ix_chapters_id', 'chapters', ['id'], unique=False)
    op.drop_index(op.f('ix_units_title'), table_name='units')
    op.drop_index(op.f('ix_units_school_year'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
