"""add datetime

Revision ID: 3d37a7bfde69
Revises: 5008afc4418e
Create Date: 2023-07-14 04:32:29.023749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d37a7bfde69'
down_revision = '5008afc4418e'
branch_labels = None
depends_on = None

from datetime import datetime

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('created_at', sa.DateTime(), default=datetime.now(), nullable=False))
    op.add_column('units', sa.Column('updated_at', sa.DateTime(), default=datetime.now(), nullable=False))
    op.drop_index('ix_units_title', table_name='units')
    op.create_index(op.f('ix_units_title'), 'units', ['title'], unique=True)
    op.add_column('problems', sa.Column('created_at', sa.DateTime(), default=datetime.now(), nullable=False))
    op.add_column('problems', sa.Column('updated_at', sa.DateTime(), default=datetime.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'updated_at')
    op.drop_column('problems', 'created_at')
    op.drop_index(op.f('ix_units_title'), table_name='units')
    op.create_index('ix_units_title', 'units', ['title'], unique=False)
    op.drop_column('units', 'updated_at')
    op.drop_column('units', 'create_at')
    # ### end Alembic commands ###
