"""create tables

Revision ID: 4e1d908f623b
Revises: 
Create Date: 2023-07-14 00:50:14.863093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1d908f623b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('school_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_chapters_school_year'), 'chapters', ['school_year'], unique=False)
    op.create_index(op.f('ix_chapters_title'), 'chapters', ['title'], unique=False)
    op.add_column('problems', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problems', 'chapters', ['chapter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'chapter_id')
    op.drop_index(op.f('ix_chapters_title'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_school_year'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    # ### end Alembic commands ###
