"""empty message

Revision ID: 5008afc4418e
Revises: 
Create Date: 2023-07-14 02:14:38.489672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5008afc4418e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('school_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_school_year'), 'units', ['school_year'], unique=False)
    op.create_index(op.f('ix_units_title'), 'units', ['title'], unique=False)
    op.add_column('problems', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.alter_column('problems', sa.Column('title', sa.String(length=100), nullable=True))
    op.alter_column('problems', sa.Column('statement', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'problems', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'unit_id')
    op.drop_index(op.f('ix_units_title'), table_name='units')
    op.drop_index(op.f('ix_units_school_year'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
